import Head from "next/head";
import Landing from "./Landing";
import Login from "./Login";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Discord | Main Page</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href='https://japaniste.fr/wp-content/uploads/2019/12/discord-logo-logodownload-download-logotipos-1.png'
        />
      </Head>

      <Landing />
    </div>
  );
}
