import { Box, Grid, Flex, Heading, Text } from "@chakra-ui/react";
import LoginForm from "./components/Login Components/LoginForm";
import Head from "next/head";

function Login() {
  return (
    <>
      <Head>
        <title>Discord | Login</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href='https://japaniste.fr/wp-content/uploads/2019/12/discord-logo-logodownload-download-logotipos-1.png'
        />
      </Head>
      <Flex
        h='100vh'
        bgImage="url('https://images.wallpaperscraft.com/image/mountains_sunset_landscape_147439_2560x1080.jpg')"
        bgPosition='center'
        bgRepeat='no-repeat'
        bgSize='cover'
        justifyContent='center'
        alignItems='center'
      >
        <Grid
          templateColumns='430px auto'
          padding='30px'
          w='700px'
          h='450px'
          bg='#36393F'
          borderRadius='5px'
          boxShadow='0 3px 10px rgba(0,0,0,0.5)'
        >
          <Box>
            <Heading as='h1' fontSize='25px' color='#fff'>
              Welcome buddy!
            </Heading>

            <Text color='gray' marginTop='5px' marginBottom='20px'>
              We're so excited to see you here!
            </Text>

            <LoginForm />
          </Box>
        </Grid>
      </Flex>
    </>
  );
}

export default Login;
